In [ ]:
# Toy representation of the perceptron learning algorithm

# Ref. Marsland p. 26

In [1]:
import numpy as np

In [30]:
M=3 # number of nodes
N=2 # number of neurons

nData = np.array([[1,2,3],[7,8,9]])
array_activation = np.zeros((M,N))
array_weight = 0.1*np.random.random((M,N))


for num_data in range(0,len(nData)): # loop over input vectors
    
    print("Num data: " + str(num_data))
    
    inputs = nData[num_data]
    
    for num_nur in range(N): # loop over neurons
        
        print("Num neuron: " + str(num_nur))
        
        # compute sum of weights times inputs for each neuron
        
        # set activation to 0 to start
        #array_activation[num_data][num_nur] = 0
        
        # loop over input nodes
        for num_node in range(0,M):
            
            print("Num node: " + str(num_node))
            
            array_activation[num_data,num_nur] += array_weight[num_node,num_nur] * nData[num_data,num_node]
            
        # now decide whether the neuron fires or not
        if array_activation[num_data,num_nur] > 0:
            array_activation[num_data,num_nur] = 1
        else:
            array_activation[num_data,num_nur] = 0
            
        print("Activation array:")
        print(array_activation)
        
        print("---------------")

Num data: 0
Num neuron: 0
Num node: 0
Num node: 1
Num node: 2
Activation array:
[[1. 0.]
 [0. 0.]
 [0. 0.]]
---------------
Num neuron: 1
Num node: 0
Num node: 1
Num node: 2
Activation array:
[[1. 1.]
 [0. 0.]
 [0. 0.]]
---------------
Num data: 1
Num neuron: 0
Num node: 0
Num node: 1
Num node: 2
Activation array:
[[1. 1.]
 [1. 0.]
 [0. 0.]]
---------------
Num neuron: 1
Num node: 0
Num node: 1
Num node: 2
Activation array:
[[1. 1.]
 [1. 1.]
 [0. 0.]]
---------------
